# -*- coding: utf-8 -*-
"""Voice_assistant.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19IhVMAZkrsedGEs436wURZ_EW5RspF4R
"""

#installing dependencies
 
!pip install SpeechRecognition
!pip install gTTS
!pip install wikipedia
!pip install PyAudio

#importing libraries
import os
from gtts import gTTS
import datetime
import warnings
import calendar
import random
import wikipedia
import speech_recognition as sr

#ignore any warnings
warnings.filterwarnings('ignore')

#Function to record audio and return its a string
def recordaudio():
    #record the audio
    r=sr.Recognizer()
    #open the mic and start recording
    with sr.Microphone() as source:
         print('Say Something!')
         audio=r.listen(source)
    #use google speech recognition
    data=''
    try:
       data=r.recognize_google(audio)
       print('You said: ' + data)
    except sr.UnknownValueError:
       print("Google Can't Understand the audio, unknown error")
    except sr.RequestError as e:
       print('Request results error'+e)
    return data

#Function to get the virtual assistant response
 
def assistantresponse(text):
    print(text)
    #convert text to speech
    myobj=gTTS(text=text,lang='en',slow=False)
    #save the converted audio to file
    myobj.save('assistance_response.mp3')
    #play the audio
    os.system('start assistance_response.mp3')

#wake word for our assistant
def wakeword(text):
    WAKE_WORDS=['hey shiv','hello shiv','okay shiv']
    text.lower()#converting into lower case
    #check to see if the users command contains a wake word
    for word in WAKE_WORDS:
        if word in text:
           return True
    #if the wake word is not found
    return False

#To give current data
def getDate():
    now=datetime.datatime.now()
    my_date=datetime.datetime.today()
    weekday=calendar.day_name[my_date.weekday()]
    monthNum=now.month
    dayNum=now.day
    #list of months
    month_names=["January","February","March","April","May","June","July","August","September","October","November","December"]
    #list of ordinal numbers
    ordinal_Numbers=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th', '11th', '12th', '13th', '14th', '15th', '16th', '17th', '18th', '19th','20th', '21st', '22nd', '23rd', '24th', '25th', '26th', '27th', '28th','29th', '30th', '31st']
    return 'Today is '+weekday+' '+month_names[monthNum-1]+' '+ 'the'+ ordinal_Numbers[dayNum-1] +'.'

#greeting text
def greeting(text):
    GREETING_INPUTS=['hi','hey!','hola','wassup','hello']
    #greeting_responses
    greeting_responses=[]
    greeting_responses=['howdy','hello','hey there']
    for greet in text.split():
        if greet.lower() in GREETING_INPUTS:
           return random.choice(greeting_responses)+'.'
    return ' '

#get the name of the person from text
def getperson(text):
    wordlist=text.split()
    for i in range(0,len(wordlist)):
       if i+3<=len(wordlist)-1 and wordlist[i].lower()=='who' and wordlist[i+1].lower()=='is':
          return wordlist[i+2]+' '+wordlist[i+3]

while True:
     #record the audio
     text=recordaudio()
     response=''
     #checking for wake word
     if (wakeword(text)==True):
        print ('This is Shiv! Assistant for you...')
        #check for greetings
        response=response+greeting(text)
        #check to see it if the user said anything
     if('date' in text):
       get_date=get_Date()
       response=response+' '+get_date
     #user says anything of time
     if('time' in text):
       now=datetime.datetime.now()
       meridiem=''
       if now.hour>=12:
          meridiem='p.m.'
          hour=now.hour-12
       else:
          meridiem='a.m.'
          hour=now.hour
       if now.minute<10:
          minute='0'+str(now.minute)
       else:
          minute=str(now.minute)
       response=response+' '+'It is '+ str(hour)+':'+minute+' '+meridiem+'.'
       
     #check to see if the user said who is
     if('who is' in text):
       person=getperson(text)
       wiki=wikipedia.summary(person, Sentences=2)
       response=response+' '+wiki
     #return audio
     assistantresponse(response)